In [ ]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
filename = '/content/drive/MyDrive/bigdata_analysis_final_project - movie recommender system(영화 추천 시스템)/Data Preprocessing/movie_dataset.csv'
movies_dataset_df = pd.read_csv('/content/drive/MyDrive/bigdata_analysis_final_project - movie recommender system(영화 추천 시스템)/Data Preprocessing/movie_dataset.csv')
movies_dataset_df.head()

movieId  naver_code                        title  title_kor  \
0        1       17153                    Toy Story     토이 스토리   
1        2       17440                      Jumanji        쥬만지   
2        4       17798            Waiting To Exhale   사랑을 기다리며   
3        5       17754  Father Of The Bride Part II  신부의 아버지 2   
4        6       17327                         Heat         히트   

                                        genres  \
0  Adventure Animation Children Comedy Fantasy   
1                   Adventure Children Fantasy   
2                         Comedy Drama Romance   
3                                       Comedy   
4                        Action Crime Thriller   

                                             keyword         director  \
0  jealousy,toy,boy,friendship,friends,rivalry,bo...    John Lasseter   
1  board game,disappearance,based on children's b...     Joe Johnston   
2  based on novel,interracial relationship,single...  Forest Whitaker   
3  baby,midlife crisis,confidence,aging,daughter,...    Charles Shyer   
4  robbery,detective,bank,obsession,chase,shootin...     Michael Mann   

                                            cast director_kor  \
0                Tom Hanks,Tim Allen,Don Rickles        존 라세터   
1     Robin Williams,Jonathan Hyde,Kirsten Dunst        조 존스톤   
2  Whitney Houston,Angela Bassett,Loretta Devine     포레스트 휘태커   
3         Steve Martin,Diane Keaton,Martin Short       찰스 샤이어   
4            Al Pacino,Robert De Niro,Val Kilmer        마이클 만   

                       cast_kor  ...  naver_user_participate  \
0                   톰 행크스, 팀 알렌  ...                    1393   
1  로빈 윌리엄스, 커스틴 던스트, 데이빗 알란 그리어  ...                    1591   
2      휘트니 휴스턴, 안젤라 바셋, 로레타 드바인  ...                      17   
3          스티브 마틴, 다이안 키튼, 마틴 숏  ...                      13   
4               알 파치노, 로버트 드 니로  ...                    1454   

   naver_critics_rate  naver_critics_participate  nation  \
0                 0.0                          0      미국   
1                 0.0                          0      미국   
2                 0.0                          0      미국   
3                 0.0                          0      미국   
4                 8.0                          1      미국   

            release_date running_time          age  \
0  2010.05.05 1995.12.30         77분     전체 관람가, G   
1             1996.01.20        104분    전체 관람가, PG   
2             1996.04.05        127분   청소년 관람불가, R   
3             1996.05.04        106분   15세 관람가, PG   
4  2017.11.09 1996.08.10        170분   청소년 관람불가, R   

                                               story  \
0  우디(톰 행크스 목소리 분)는 6살짜리 남자 아이 앤디가 가장 아끼는 카우보이 인형...   
1  1969년. 커다란 공장을 운영하는 아버지를 둔 12세 소년 알랜 패리쉬(Young...   
2  사반나 잭슨(Savannah Jackson: 휘트니 휴스턴 분)은 TV 프로듀서로서...   
3  사랑하는 딸을 시집보내고 난 뒤, 한동안 허전함을 극복하지 못했던 '신부의 아버지'...   
4  LA 경찰국 강력계의 빈센트 한나(알 파치노) 반장은 두 번의 이혼 경력과 순탄치 ...   

                                          poster_url  \
0  https://movie-phinf.pstatic.net/20111222_26/13...   
1  https://movie-phinf.pstatic.net/20111223_209/1...   
2  https://movie-phinf.pstatic.net/20111221_192/1...   
3  https://movie-phinf.pstatic.net/20111222_214/1...   
4  https://movie-phinf.pstatic.net/20171024_181/1...   

                                                 url  
0  https://movie.naver.com/movie/bi/mi/basic.nave...  
1  https://movie.naver.com/movie/bi/mi/basic.nave...  
2  https://movie.naver.com/movie/bi/mi/basic.nave...  
3  https://movie.naver.com/movie/bi/mi/basic.nave...  
4  https://movie.naver.com/movie/bi/mi/basic.nave...  

[5 rows x 21 columns]

In [ ]:
# 개인 맞춤 장르요소 새로운 행추가
# 213 -> 'Action Action Action Adventure Adventure Thriller Thriller Sci-Fi Sci-Fi Drama'
# 475 -> 'Drama Drama Drama Action Action Action Thriller Thriller Adventure Sci-Fi'
# 288 -> 'Comedy Comedy Comedy Action Action Action Drama Drama Adventure Adventure Romance'
# 64 -> 'user64_taste' ,'genres' : 'Drama Drama Drama Action Action Adventure Adventure Thriller Comedy'
new_data = {'title': 'user64_taste' ,'genres' : 'Drama Drama Drama Action Action Adventure Adventure Thriller Comedy'}
movies_dataset_df = movies_dataset_df.append(new_data, ignore_index=True)

In [ ]:
movies_dataset_df.tail(1)

movieId  naver_code         title title_kor  \
3964      NaN         NaN  user64_taste       NaN   

                                                 genres keyword director cast  \
3964  Drama Drama Drama Action Action Adventure Adve...     NaN      NaN  NaN   

     director_kor cast_kor  ...  naver_user_participate  naver_critics_rate  \
3964          NaN      NaN  ...                     NaN                 NaN   

      naver_critics_participate  nation release_date running_time  age story  \
3964                        NaN     NaN          NaN          NaN  NaN   NaN   

     poster_url  url  
3964        NaN  NaN  

[1 rows x 21 columns]

In [ ]:
count_vect = CountVectorizer(min_df=0, ngram_range=(1,2))
genre_mat = count_vect.fit_transform(movies_dataset_df['genres'])
print(genre_mat.shape)

(3965, 164)


In [ ]:
genre_sim = cosine_similarity(genre_mat, genre_mat)
print(genre_sim.shape)
print(genre_sim[:2])

(3965, 3965)
[[1.         0.4472136  0.1490712  ... 0.         0.         0.18569534]
 [0.4472136  1.         0.         ... 0.         0.         0.16609096]]


In [ ]:
genre_sim_sorted_ind = genre_sim.argsort()[:, ::-1]
print(genre_sim_sorted_ind[:1])

[[   0 2459  440 ... 1835 3253 1982]]


In [ ]:
percentile = 0.6
m = movies_dataset_df['naver_user_participate'].quantile(percentile)
C = movies_dataset_df['naver_user_rate'].mean()

def weighted_rating_average(record):
    v = record['naver_user_participate']
    R = record['naver_user_rate']
    
    return ( (v/(v+m)) * R ) + ( (m/(m+v)) * C )   

movies_dataset_df['weighted_rate'] = movies_dataset_df.apply(weighted_rating_average, axis=1) 

In [ ]:
movies_dataset_df[['title','naver_user_rate','weighted_rate','naver_user_participate']].sort_values('weighted_rate', ascending=False)[:10]

title  naver_user_rate  weighted_rate  \
3841            Band Of Brothers             9.73       9.410353   
373                      Titanic             9.41       9.383097   
195   Terminator 2: Judgment Day             9.45       9.368184   
117                 Forrest Gump             9.42       9.347925   
1935                    3 Idiots             9.35       9.326742   
1991                 Toy Story 3             9.40       9.321688   
3481                 Be With You             9.35       9.311933   
420          Saving Private Ryan             9.43       9.306090   
279           Dead Poets Society             9.38       9.300176   
192                   Home Alone             9.43       9.296718   

      naver_user_participate  
3841                  1966.0  
373                  23052.0  
195                   7525.0  
117                   8457.0  
1935                 25932.0  
1991                  7682.0  
3481                 15726.0  
420                   4817.0  
279                   7455.0  
192                   4457.0

In [ ]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
  title_movie = df[df['title'] == title_name]
  title_index = title_movie.index.values
    
  similar_indexes = sorted_ind[title_index, :(top_n*2)]
  similar_indexes = similar_indexes.reshape(-1)

  similar_indexes = similar_indexes[similar_indexes != title_index]

  result_df = df.iloc[similar_indexes].sort_values('weighted_rate', ascending=False)[:top_n]
  result_df = result_df[['movieId', 'title', 'title_kor', 'genres', 'poster_url']]
  result_df.reset_index(drop=True, inplace=True)
  result_df.reset_index(drop=False, inplace=True)
  result_df.rename(columns={'index':'rank'}, inplace=True)
  result_df['rank'] = result_df['rank'] + 1
    
  return result_df

In [ ]:
recomm_movies = find_sim_movie(movies_dataset_df, genre_sim_sorted_ind, 'user64_taste',5)
recomm_movies['movieId'] = recomm_movies['movieId'].astype('int')
recomm_movies

rank  movieId                             title         title_kor  \
0     1   141072                 The Divine Weapon               신기전   
1     2   131444  Rurouni Kenshin: The Legend Ends  바람의 검심 : 전설의 최후편   
2     3       86                      White Squall            화이트 스콜   
3     4   110968                           Pompeii        폼페이: 최후의 날   
4     5    94780       Snow White And The Huntsman   스노우 화이트 앤 더 헌츠맨   

                   genres                                         poster_url  
0  Action Adventure Drama  https://movie-phinf.pstatic.net/20111222_186/1...  
1  Action Adventure Drama  https://movie-phinf.pstatic.net/20150223_141/1...  
2  Action Adventure Drama  https://movie-phinf.pstatic.net/20111222_165/1...  
3  Action Adventure Drama  https://movie-phinf.pstatic.net/20140213_66/13...  
4  Action Adventure Drama  https://movie-phinf.pstatic.net/20120529_80/13...

In [ ]:
recomm_movies.to_csv("contents_based_filtering_list(genre).csv", mode='w', index=False)

### end of file

In [ ]:
# 영화 추천 시스템 캐글 코드 보충